test = {   'name': 'q36',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> santa_barbara_markets.num_rows == 5\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': ">>> list(santa_barbara_markets.column('city')) == ['Santa Barbara', 'Santa Barbara', 'Santa Barbara','Santa Barbara','Santa Barbara']\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
